# Author: JRR ----
# Maintainers: JRR, AF, OE 
# Copyright:   2023, Data Cívica v2 or later
# ===========================================================


# FISCALIA  ---------------------------------------------------------------
TOLUCA <- list("TOLUCA, EN PROCESO LA DENUNCIA", "TOLUCA SUSTRACCION DE HIJO", "TOLUCA POR SUSTRACCION DE HIJO",
               "TOLUCA POR SUSTRACCION DE HIJ", "TOLUCA FISCALIA DESAPARECIOS", "AMP TOLUCA", "ANTISECUESTROS TOLUCA",
               "CENTRO DE JUSTICIA TOLUCA", "DESAPARECIDOS TOLUCA", "FISCALIA DE DESAPARECIDOS TOLU")


TLALNEPANTLA <- list("FISCALIA REGIONAL TLALNEPANTLA", "AMP TLALNEPANTLA", "FISCALIA REGIONAL DE TLALNEPAN", 
                     "FISCALÍA REGIONAL DE TLALNEPAN", "AMP TLALNEPANTLA DE BAZ", "AMP TLALNEPANTLA MEXICO",
                     "AMP DE TLALNEPANTLA DE BAZ", "TLALNEPANTLAN", "AMP DE TLALNEPANTLA DE BAZ",
                     "AMP TLALNEPANTLA MEXICO", "EN TLALNEPANTLA", "FISCALIA DE TLALNEPANTLA",
                     "FISCALIA REOGINAL DE TLALNEPAN", "MINITERIO PUBLICO TLALNEPANTLA", "TLALANEPANTLA",
                     "TLALNEPANTLA DE BAZ", "TLANEPANTLA")



NEZAHUALCOYOTL <- list("FISCALIA REGIONAL NEZAHUALCOYO", "AMP NEZAHUALCOYOTL", "NEZAHUALCÓYOTL",
                       "PALACIO NEZAHUALCOYOTL", "AMP DE NEZAHUALCOYOTL", "DENUNCIA EN PROCESO NEZAHUALC",
                       "GENRO FISCALIA REGIONAL NEZAHU", "MINISTERIO PUBLICO NEZAHUALCOY", 
                       "NEZAHALCOYOTL", "NEZAHUACÓYOTL", "NEZAHUALCOYL", "NEZAHUALCOYOLT",
                       "NEZAHUALCOYOT", "NEZAHUALCÓYOTL (LA PERLA)", "NEZAHUALCOYOTL PALACIO",
                       "NEZAHUALCOYOTOTL", "NEZAHUALCOYTL", "PALACIO MUNICIPIAL DE NEZA", 
                       "SEDE EN NEZAHUALCÓYOTL")



ECATEPEC <- list("CENTRO DE JUSTICIA DE ECATEPEC", "AMP ECATEPEC", "FISCALÍA REGIONAL DE ECATEPEC",
                 "SAN AGUSTIN ECATEPEC", "FISCALÍA REGIONAL DE ECATEPEC", "ECATEPEC DE MORELOS",
                 "FISCALIA REGIONAL ECATEPEC", "LAS PALMAS ECATEPEC", "AMP DE ECATEPEC",
                 "CENTRO DE JUSTICIA ECATEPEC", "AMP ECATEPEC DE MORELOS", "AMP´ECATEPEC", 
                 "AMPECATEPEC", "CENTRO DE JUSTICIA DE ECATEPE", "CENTRO JUSTICIA ECATEPEC",
                 "CETRO DE JUSTICIA ECATEPEC", "ECATEPEC SAN AGUSTIN", "ECATEPEC, SAN AGUSTIN",
                 "ECATEPEC.", "ECATEPER", "FISCALIA REGIONAL DE ECATEPEC", "MINISTERIO PUBLICO DE ECATEPEC",
                 "REGIONAL ECATEPEC", "SAN CRISTOBAL ECATEPEC")


AMECAMECA <- list("FISCALÍA REGIONAL DE AMECAMECA", "FISCALIA REGIONAL AMECAMECA", 
                  "AMECAMENCA", "AMACAMECA", "AMECA", "AMP AMECAMECA")



CUAUTITLAN <- list("CUATITLAN IZCALLI", "CUAUTITLAN IZCALLI", "CUATITLAN", "AMP CUAUTITLAN IZCALLI",
                   "CUATITLAN MEXICO", "AMP CUAUTITLAN", "FISCALIA REGIONAL CUAUTITLÁN I",
                   "CUAUTITLÁN IZCALLI", "CUAUTITLAN MEXICO", "CUAUTITLÁN MÉXICO", 
                   "MP CUAUTITLAN", "AMP CUAUTITLAN DE ROMERO", "AMP CUAUTITLAN MEXICO",
                   "CUAUTITLÁN", "FISCALIA DE CUAUTITLAN IZCALLI", "CUATILAN IZCALLI",
                   "CUAUTITLÁN DE ROMRO RUBIO", "CUAUTITLAN RUBIO", "FISCALÍA REGIONAL DE CUAUTITLÁ",
                   "REGIONAL CUAUTITLAN", "IZCALLI")



TEXCOCO <- list("FISCALIA REGIONAL TEXCOCO", "AMP TEXCOCO", "FISCALÍA REGIONAL DE TEXCOCO",
                "FISCALÍA REGIONAL DE TEXCOCO,", "FISCALÍA REGIONAL TEXCOCO", "DESAPARECIDOS TEXCOCO",
                "FISCALIA DE TEXCOCO", "FISCALIA REGIONAL DE TEXCOCO", "FISCALIA TEXCOCO",
                "MP TEXCOCO", "REGIONAL DE TEXCOCO", "TEXCOCO, ESTADO DE MEXICO", "TEXCOCOJEFA DE PROYECTO B")



ATLACOMULCO <- list("AMP ATLACOMULCO", "FISCALÍA REGIONAL DE ATLACOMUL", "AMPEVFSG ATLACOMULCO",
                    "AMPP ATLACOMULCO", "ATL/ATA/03/MPI/918/00978/20/04", "ATL/ATA/03/MPI/918/00978/20/04",
                    "ATLACOOMULCO", "FISCALIA REGIONAL ATLACOMULCO", "FISCALÍA REGIONAL ATLACOMULCO",
                    "TLANEPNATLA")



IXTAPAN_DE_LA_SAL <- list("FISCALIA REGIONAL IXTAPAN DE L", "FISCALÍA REGIONAL DE IXTAPAN D",
                            "CENTRO DE JUSTICIA DE IXTAPALU", "IXTAPA DE LA SAL",
                            "FISCALÍA REGIONAL IXTAPAN DE L", "IXTAPAN DE LA SAL")


NAUCALPAN <- list("AMP NAUCALPAN", "FISCALIA REGIONAL NAUCALPAN", "AMP DE NAUCALPAN",
                  "AMP NAUCAÑPAN", "CENTRO DE JUSTICIA NAUCALPAN", "CENTRO JUSTICIA NAUCALPAN",
                  "FISCALIA DE DESAPARECIDOS NAUC", "FISCALIA DE NAUCALPAN", "FISCALIA DESAPARECIDOS NAUCALP",
                  "NAUCLAPAN")

TEJUPILCO <- list("FISCALIA REGIONAL TEJUPILCO", "FISCALIA REGIONAL DE TEJUPILCO")


VALLE_DE_BRAVO <- list("VALLE DE BRAVO", "AMP VALLE DE BRAVO", "FISCALIA REGIONAL VALLE DE BRA",
                       "CENTRO DE JUSTICA DE VALLE DE", "CENTRO DE JUSTICIA DE VALLE DE",
                       "CENTRO DE JUSTICIA D EVALLE DE", "FISCALIA DE VALLE DE BRAVO", 
                       "FISCALIA REGIONAL DE VALLE DE", "VALLE BRAVO")


CHALCO <- list("VALLE DE CHALCO", "AMP VALLE DE CHALCO", "AMP CHALCO", 
               "DESAPARECIDOS DE CHALCO ESTADO", "AMPEVFSG VALLE DE CHALCO",
               "CENTRO DE JUSTICIA DE CHALCO", "FISCALIA DE VALLE DE CHALCO", 
               "VALE DE CHALCO", "VALLE CHALCO", "CENTRO DE JUSTICIA VALLE DE CH")



TECAMAC <- list("AMP TECAMAC", "FISCALIA REGIONAL TECAMAC", "CENTRO DE JUSTICA TECAMAC",
                "FISCALA DE TECAMAC", "FISCALIA REGIONAL DE TECAMAC", "FISCALÍA TECAMAC",
                "HEROES DE TECAMAC", "HEROES TECAMAC", "MINISTERI PUBLICO TECAMAC",
                "TECAMAC.", "TECAMACA", "TECÁMAC")


CHIMALHUACAN <- list("AMP CHIMALHUACAN", "CHIMALHUACÁN", "AMP DE CHIMALHUACAN",
                     "FISCALIA DE CHIMALHUACAN")

IXTAPALUCA <- list("AMP IXTAPALUCA", "CENTRO DE JUSTICIA DE IXTAPALU", "AMPEVIS IXTAPALUCA",
                   "CENTRO DE JUSICIA IXTAPALUCA", "FISCALIA IXTAPALUCA",
                   "IXTALUCA", "REGIONAL IXTAPALUCA")


TULTITLAN <- list("AMP TULTITLAN", "FISCALIA TULTITLAN", "TULTILAN")


ATIZAPAN <- list("ATIZAPAN DE ZARAGOZA", "ATIZAPAN", "AMP ATIZAPAN", "ATIZAPÁN DE ZARAGOZA",
                 "AMP ATIZAPAN DE ZARAGOZA", "ATIZAOAN DE ZARAGOZA", "CENTRO DE JUSTICIA ATIZAPAN DE")


NICOLAS_ROMERO <- list("NICOLAS ROMERO", "AMP NICOLAS ROMERO", "MP TURNO UNICO EL ORO",
                       "FISCALIA DE NICOLAS ROMERO")


JILOTEPEC <- list("CENTRO DE JUSTICIA JILOTEPEC", "MINISTERIO PÚBLICO DE JILOTEPE",
                  "CENTRO DE JUSTICIA DE JILOTEPE")


COACALCO <- list("CENTRO DE JUSTICIA DE COACALCO", "COACALCO BERRIOZABAL",
                 "COACALCO DE BERRIOZABAL", "FISCALIA DE COACALCO")



NO_EDOMEX <- list("CIUDAD DE MEXICO", "AZCAPOZALCO", "CD MX, CABEZA DE JUAREZ",
                  "CDMX", "CIUDAD DE MÉXICO", "CIUDAD DE MEXICO FIPEDE", "CIUDAD DE MEXICO.",
                  "COMISION DE BUSQUEDA DE TLAXCA", "DELEGACION DE TLALPAN",
                  "DENUNCIA EN CDMX.", "ESTADO DE VERACRUZ", "FISC. SUR PTE. EDO. DE MORELOS",
                  "FISCALIA DE BAJA CALIFORNIA", "FISCALIA DE PUEBLA", "FISCALIA GENERAL DE LA REPUBLI",
                  "FISCALIA GENERAL DE QUERÉTARO", "FISCALIA TAPACHULA CHIAPAS",
                  "HIDALGO GUERRERO", "LAGOS DE MORENO JALISCO", "MICHOACAN", "MP CIUDAD DE MEXICO",
                  "QUERETARO", "SAN LUIS POTOSI", "SECUESTRO DE VALLE DE MEXICO", "TLALPAN",
                  "ZACATECAS")


IXTLAHUACA <- list("AMP IXTLAHUACA", "AMP DE IXTLAHUACA", "CENTRO JUSTICIA IXTLAHUACA",
                   "IXTLAHUACA.", "MINISTERIO PÚBLICO DE IXTLAHUA")



# Categoria  --------------------------------------------------------------
VOLUNTARIA <- list("CONVIVENCIA CON AMIGOS / EVENTO SOCIAL", "ACTIVIDAD LABORAL", "PROBLEMAS DE CONDUCTA",
                "INGRESO A CENTRO DE REHABILITACION", "DESORIENTACION CIRCUNSTANCIAL", "ENFERMEDADES Y OTROS PROBLEMAS DE SALUD",
                "ACCIDENTE", "TRASTORNO MENTAL", "ADICCION", "DISCAPACIDAD", "USO DE SUSTANCIAS", "PROBLEMAS DE ADICCION",
                "CONVIVENCIA CON AMIGOS/EVENTO SOCIAL", "VINCULACIÓN FAMILIAR", "ENFERMEDAD", "INGRESO A CENTRO DE REHABILITACIÓN",
                "CONDUCTA", "POR ENFERMEDAD",  "ADICCIONES", "AUSENCIA VOLUNTARIA POR AMIGOS",
                "AUSENCIA VOLUNTARIA POR FIESTA", "CONVIVENCIA CON AMIGOS", "DEHAMBULANDO", "DESASTRE NATURAL",
                "EGRESO DE UN CENTRO DE REHABILITACION", "ENGERMEDAD MENTAL", "EXTRAVIO REAL",
                "INGERIR BEBIDAS ALCOHÓLICAS", "INGRESADA A UN ALBERGUE", "INGRESO A CENTRO DE RECUPERACIÓN",
                "PROBLEMA DE CONDUCTA", "PROBLEMAS DE CONDUCTA.", "PROCESO LEGAL", "SE FUE DE PINTA CON SUS AMIGOS."
                )

INVOLUNTARIA <- list("VICTIMA", "LOCALIZADO SIN VIDA", "CONFLICTOS CON PARTICULARES",
                  "LOCALIZADA SIN VIDA", "DETENCION", "PRIVACIÓN DE LIBERTAD", "DETENIDO", "DETENCIÓN",
                  "DETENIDO .", "DETENIDO.", "PRIVACIÓN", "PRIVACION DE LA LIBERTAD", "ROBO",
                  "SIN VIDA", "VICTIMA DE DELITO", "VIOLENCIA"
                  )

COMPLEJA <- list("RELACION DE PAREJA", "VINCULACION FAMILIAR", "CONFLICTO EMOCIONAL", "CONFLICTOS CON LA LEY",
              "PROBLEMAS FAMILIARES", "MIGRACION", "FALTA DE COMUNICACION", "NOVIAZGO", "PROBLEMAS DE COMUNICACION",
              "POR NOVIAZGO", "RELACIÓN DE PAREJA", "VIOLENCIA FAMILIAR", "DISTURBIO SOCIAL",
              "FALTA DE COMUNICACION CON FAMILIA", "CONFLICTOS FAMILIARES", "FALTA DE COMUNICACIÓN",
              "RELACION SENTIMENTAL", "FALLECIMIENTO", "FALTA DE COMUNCIACION", "FALTA DE COMUNICACION CON LA FAMILIA",
              "FALTA DE COMUNICAION CON FAMILIARES", "IMPOSIBILIDAD PARA REGRESAR", "MIGRACIÓN",
              "PROBLEMA DE COMUNICACION", "PROBLEMA FAMILIAR", "PROBLEMAS FAMILIAR", "SITUACION FAMILIAR",
              "SUSTRACCION PARENTAL", "SUSTRACCION PARENTAL.", "VIOLENCIA POR PARTE DE SU PADRE.",
              "PROBLEMAS PERSONALES", "CONFLICTO FAMILIAR"
              )

NO_ESPECIFICADO_CAT <- list("NO ESPECIFICADA", "NO ESPECIFICADO", "NO SE ESPECIFICA",
                            "NO ESPECIFICA", "SIN ESPECIFICAR", "NO ESPECIFICO", 
                            "SE DESCONOCE", "X", "NO ESPECIICADA", "NO SE ESPECIFICA.",
                            "NO SE ESPICIFICA", "NO SE INDICA", "NO SE TIENE LA INFORMACIÓN",
                            "SIN ESPACIFICAR", "SIN INFORMACION", "SIN PRECISAR")


# NACIONALIDAD  -----------------------------------------------------------
MEXICANA <- list("MEXICANA", "ESTADO DE MEXICO", "MEXICANA Y DE REPUBLICA DOMINICANA", 
                 "MEXICANA Y EXTRANJERA", "MEXICANA, ESTADOUNIDENSE", 
                 "MEXICANA, EXTRANJERA", "MEXICANA/AMERICANA",
                 "MXICANA", "PONIETE", "TOLUCA")


# Estado civil  -----------------------------------------------------------

soltero <- list("SOLTERO(A)", "SOLTERO", "SOLTERA", "MENOR",
                "NINGUNA", "ESTUDIANTE", "MENOR DE EDAD", "SOLTEROO",
                "SOLTRO", "SOTERO", "MADRE SOLTERA", "PRIMARIA",
                "SOLERO", "SOLTEO", "SOLTERA.", "SOTLERO",
                "AOLTERA", "CELULAR", "EMPLEADA", "MMENOR",
                "MANE MALAQUIAS", "NINGUNO", "SALTERA", 
                "SAOLTERO", "SECUN", "SECUNDARIA", "SLTER",
                "SOLERA", "SOLERTO", "SOLETRO",
                "SOLOTERA", "SOLOTERO", "SOLTEA",
                "SOLTER0", "SOLTERAA", "SOLTERERA", "SOLTERO(AO)",
                "SOLTERO.", "SOLTEROA", "SOLTERO|", "SOLTERQ", "SOLTERRO",
                "SOOLTERA", "SOTERA")


pareja <- list("UNION LIBRE", "CASADO(A)", "CASADO", "CASADA", "CASADOS",
               "CADASO", "CASDA", "CONCUBINO", "CADASA", "CASA",
               "CASADA (SE PRESUME)", "CASADDO", "CASADO(A).",
               "CASADO/ SEPARADO", "CASADOP", "CASASA", "CASD",
               "CIVIL", "CONCUBINA", "CSADA", "CUNION LIBRE",
               "DCASADO", "DDIVORCIADO", "ESPOSA", "SCASA", "UINON LIBRE",
               "UNIN LIBRE", "UNIO LIBRE", "UNION LIBRRE",
               "UNION LOIBRE", "UNION RELIGIOSA", "UNION SOLTERA",
               "UNIONLIBRE", "UNON LIBRE")


divorciado <- list("DIVORCIADO(A)", "DIVORCIADO", "SEPARADO", "SEPARADA",
                   "DIVORCIADA", "EPARADO", "SEPARADO.")


viudo <- list("VIUDO(A)", "VIUDO", "VIUDA", "VUIDO", ".VIUDA", "VIUD")



# Escolaridad  ------------------------------------------------------------

preescolar <- list("PREESCOLAR", "KINDER", "PRE ESCOLAR", "GUARDERIA",
                   "PRIMARIA INCOMPLETA", "PRIMARIA TRUNCA", "PRESCOLAR",
                   "3° KINDER", "2° KINDER", "1° KINDER", "2O. PREESCOLAR",
                   "1O. DE PREESCOLAR", "1° PRE ESCOLAR", "2° PRE ESCOLAR",
                   "2° PREESCOLAR", "MATERNAL", "PRE ESCOLAE", "3 ERO KINDER",
                   "3 KINDER", "3ER. KINDER", "3O PREESCOLAR", "3O. PREESCOLAR",
                   "3° PRE ESCOLAR", "3° PREESCOLAR", "3° PRESCOLAR", "JARIN DE NIÑOS",
                   "KIDER", "PRE- ESCOLAR", "PREEESCOLAR", "PREESOLAR", "PRIMARIA 3 TRUNCA",
                   "PRIMARIA INCOMPLERA", "PRIMARIA TRUCA", "PRIMARIA TRUNCA 3ER GRADO",
                   "PRIMARIO INCOMPLETA", "PRIMERO DE KINDER", "PRRESCOLAR", "SEGUNDO KINDER",
                   "TERCERO DE KINDER")


primaria <- list("PRIMARIA",
                 "3° PRIMARIA", "3° PRIMARIA", "2° PRIMARIA", "1° PRIMARIA",
                 "5° PRIMARIA", "4° PRIMARIA",
                 "SECUNDARIA INCOMPLETA", "6° PRIMARIA", "2DO PRIMARIA",
                 "1RO PRIMARIA", "5TO PRIMARIA", "3 PRIMARIA", "5 PRIMARIA",
                 "2 PRIMARIA", "5O. PRIMARIA", "PPRIMARIA", "TERCERO DE PRIMARIA",
                 "3RO PRIMARIA", "6TO PRIMARIA", "3O. PRIMARIA", "2O. PRIMARIA",
                 "4 PRIMARIA", "4TO PRIMARIA", "5 DE PRIMARIA", "PRIMARIA ABIERTA",
                 "SECUNADRIA INCOMPLETA",  "1O. DE PRIMARIA",
                 "1O. PRIMARIA", "3ERO DE PRIMARIA", "6 PRIMARIA", "PRIMARA",
                 "PRMARIA", "SEGUNDO DE PRIMARIA", "1RO DE PRIMARIA",
                 "1° DE PRIMARIA", "2 DE PRIMARIA", "3RO DE PRIMARIA",
                 "5TO DE PRIMARIA", "5TO. PRIMARIA", "PRIMARIA INCONCLUSA",
                 "PRIAMRIA", "PRIMARIA TERMINADA", "PRIMERO DE PRIMARIA",
                 "CUARTO DE PRIMARIA", "SEXTO PRIMARIA", "1 PRIMARIA", "2DO DE PRIMARIA",
                 "2O. DE PRIMARIA", "2° DE PRIMARIA", "3 DE PRIMARIA", "3ER. PRIMARIA",
                 "4 DE PRIMARIA", "5O. DE PRIMARIA", "5TO. DE PRIMARIA", "6TO AÑO DE PRIMARIA",
                 "ERO PRIMARIA", "PIMARIA", "PRIAMARIA", "PRIMARIA 4", "PRIMARIA 5",
                 "PRIMARIA INEA", "PRIMARIA SISTEMA ABIERTO", "SECUNDARIA TRUNTA",
                 "2 DO DE PRIMARIA", "2 DO. PRIMARIA", "2 PRIM", "2 PRIMRIA", "2. PRIMARIA",
                 "2DO. PRIMARIA", "2°. PRIMARIA", "3ER AÑO DE PRIMARIA", "3ER DE PRIMARIA",
                 "3° PRIMRIA", "4 AÑO DE PRIMARIA", "4. PRIMARIA", "4O. PRIMARIA",
                 "4TO AÑO DE PRIMARIA", "4TO PIRMARIA", "5O PRIMARIA", "5T0 PRIMARIA",
                 "6 TO DE PRIMARIA", "6TO AÑO PRIMARIA", "6TO DE PRIMARIA", "6° DE PRIMARIA",
                 "CUARTO DE PRMARIA", "CUARTO PRIMARIA", "DSECUNDARIA INCOMPLETA", "ERO DE PRIMARIA",
                 "INEA PRIMARIA", "PIRMARIA",  "PRIMAIA ABIERTA", "PRIMARIA (SE PRESUME)",
                 "PRIMARIA 1RO", "PRIMARIA 3 AÑO", "PRIMARIA 3°", "PRIMARIA 4 AÑO", "PRIMARIA COMPLETA",
                 "PRIMARIA CUARTO GRADO", "PRIMARIA PRIMER GRADO", 	"PRIMARIAE", "PRIMARIAS",
                 "PRIMERIA", "PRIMIARIA", "PRIMIRIA", "PRIMRIA", "QUINTO AÑO PRIMARIA", "QUINTO DE PRIMARIA",
                 "RPIMARIA", "SECUANDARIA TRUNCA", "SECUBNDARIA TRUNCA", "SECUNADARIA TRUNCA",
                 "SECUNDARIA IMCOMPLETA", "SECUNDARIA INCOMPETA", "SECUNDARIA INCONCLUSA",
                 "SEECUNDARIA TRUNCA", "SEGUNDO PRIMARIA", "SEXTO DE PRIMARIA",
                 "TERCER AÑO DE PRIMARIA", "TERCERO PRIMARIA", "SECUNDARIA TRUNCA")


secundaria <- list("SECUNDARIA", "SECUANDARIA", "SEUNDARIA",
                   "2° SECUNDARIA", "1° SECUNDARIA", "3° SECUNDARIA",
                   "SECUNADRIA", "SECUNADARIA",
                   "SECUNADARIA", "SECUDNARIA", "2 SECUNDARIA", 
                   "1 SECUNDARIA", "PREPARATORIA TRUNCA",
                   "PREPA INCOMPLETA", "BACHILLERATO INCOMPLETO",
                   "PREPA TRUNCA", "BACHILLERATO TRUNCO",
                   "PREPARATORIA INCOMPLETA", "2O. SECUNDARIA",
                   "SECUNDARIA ABIERTA", "2DO SECUNDARIA",
                   "3RO SECUNDARIA", 
                   "3O. SECUNDARIA", "2DO DE SECUNDARIA",
                   "TERCERO DE SECUNDARIA", "1RO SECUNDARIA",
                   "SECUNDARIA TERMINADA", "3 SECUNDARIA", "3RO DE SECUNDARIA",
                   "1O. SECUNDARIA", "2DO. SECUNDARIA", "PREPARATORIA INCOMPETA",
                   "SECUDARIA", "SECUNDARIA COMPLETA", "PRIMERO DE SECUNDARIA",
                   "SEGUNDO DE SECUNDARIA", "TELESECUNDARIA", "1O. DE SECUNDARIA",
                   "2. SECUNDARIA", "PREPA TRUCA", "SCUNDARIA", "SEGUNDO SECUNDARIA",
                   "1. SECUNDARIA", "3ERO. SECUNDARIA", "BACHILLERTO TRUNCA",
                   "PREPARTORIA TRUNCA", "PREPATORIA TRUNCA",
                   "PRIMERO SECUNDARIA", "SECUNDARA", "TERCERO SECUNDARIA",
                   "1ERO DE SECUNDARIA", "1RO. DE SECUNDARIA", "1| SECUNDARIA","1°SECUNDARIA",
                   "2. SECUNADARIA", "2°SECUNDARIA", "3DO SECUNDARIA", "3RO. SECUNDARIA",
                   "BACHILELRATO TRUNCA", "INEA SECUNDARIA", "PREPA TRUCO", "PREPARATORIA NO CONCLUIDA",
                   "PREPARATORIA TRUCA", "PREPARATORIA TRUNCO", "PREPARATURA TRUNCA", "SECSOL",
                   "SECUNDARIA 2DO", "SECUNDRIA", "- 2DO DE SECUNDARIA", "1 AÑO SECUNDARIA",
                   "1 DE SECUNDARIA", "1 SECUNADRIA", "12 2O. DE SECUNDARIA", "12 2O. DE SECUNDARIA",
                   "1ER GRADO DE SECUNDARIA", "1RO DE SECUNADARIA", "1RO DE SECUNDARIA",
                   "1RO SECUANDARIA", "1RO SECUNDARIO", "1ROO DE SECUNDARIA", "1° DE SECUNDARIA",
                   "1° SECUNDARIA ABIERTA", "2 SEC", "2 ° SECUNDARIA", "2.SECUNDARIA", "2D SECUN",
                   "2DE DE SECUNDARIA", "2DO DE SECUNARIA", "2DO. DE SECUNDARIA", "2O DE SECUNDARIA",
                   "2O. SECUNADRIA", "2| SECUNDARIA", "3 DE SECUNDARIA", "3 SECCUNDARIA",
                   "3 SECUNADARIA", "3 SEUNDARIA", "3ER. SECUNDARIA", "3ERO DE SECUNDARIA", 
                   "3ERO SECUNDARIA", "3O SECUNDARIA", "3RO. DE SECUNDARIA", "3° SEUNDARIA",
                   "3°SECUNDARIA", "ASECUNDARIA", "BACHILLERATO INCOMPLETA", "BACHILLERATO TRUNO", "BSECUNDARIA",
                   "CSECUNDARIA", "ECUNDARIA", "EDO SECUNDARIA", "ERO DE SECUNDARIA", "ESTÁ ESTUDIANDO SECUNDARIA ABIERTA EN EL INEA",
                   "PPREPARATORIA TRUNCA", "PREPA TRUNCA PREPA ANEXA A LA NORMAL 4", "PREPA TRUNCA, DIFEM",
                   "PREPA TURNCA", "PREPARAORIA TRUNCA", "PREPARATIORIA TRUNCA", "PREPARATORIA IMCOMPLETA",
                   "PREPARATORIA INCONCLUSA", "PREPARATORIO INCONCLUSA", "PREPARATOROA TRUNCA",
                   "PREPAROTIRIA TRUNCA", "PREPAROTORIA TRUNCA", "PREPARTATORIA TRUNCA", "PREPARTORA INCOMPLETA",
                   "PREPARTORIA INCOMPLETA", "PREPERATOTIA TRUNCA", "PREPRARATORIA INCOMPELTA", 
                   "PREPRARATORIA TRUNCA", "PRIEMRO DE SECUNDARIA", "PRIMER DE SECUNDARIA SECUNDARIA",
                   "PSECUNDARIA", "RO SECUNDARIA", "S3 SECUNDARIA", "SEC UNDARIA", "SECCCCC",
                   "SECENDARIA", "SECNDARIA", "SECUANDIRA", "SECUBDARIA", "SECUDANARIA", "SECUNADIA",
                   "SECUN DARIA", "SECUNARIA", "SECUNDARI", "SECUNDARIA 2°", "SECUNDARIA 3 ER",
                   "SECUNDARIA 3ER GRADO", "SECUNDARIA 3O.", "SECUNDARIA 3O.", "SECUNDARIA 3RO",
                   "SECUNDARIA EN PROCESO", "SECUNDARIA INEA", "SECUNDARIA INEAS",
                   "SECUNDARIA PARA ADULTOS", "SECUNDARIA SEGUNDO GRADO", "SECUNDARIA Y CULTURA DE BELLEZA",
                   "SECUNDARIA Y TECNICA", "SECUNDARIA.", "SECUNDARIAF", "SECUNDARIR",
                   "SECUNDARISA", "SECUNDAROA", "SECUNDARUA", "SECUNDIRIA", "SECUNDURIA", 
                   "SEDUNDARIA", "SEGUDO DE SECUNDARIA", "SEGUNDARIA", "SEGUNDO DE SECUANDARIA",
                   "SEGUNDO DE SECUNADARIA", "SENCUDARIA", "SESUNDARIA", "SEUNDO DE SECUNDRIA",
                   "SSECUNDARIA INCOMPLETA", "TELE SECUNDARIA", "TELESECUANDARIA", "TERCER SECUNDARIA",
                   "TERCERO DE SECUNDARIO", "3. SECUNDARIA", "2DO. DE SEGUNDARIA")


preparatoria <- list("PREPARATORIA", "BACHILLERATO",  "1° PREPARATORIA", "LICENCIATURA TRUNCA",
                     "UNIVERSIDAD TRUNCA", "CARRERA TRUNCA", 
                     "PREPERATORIA", "4° SEMESTRE PREPARATORIA", "PREPARTORIA",
                     "BACHILERATO", "BACHILLERATO CBTIS", "1° SEMESTRE PREPARATORIA",
                     "2° PREPARATORIA", "PREPAPARATORIA",
                     "5° SEMESTRE PREPARATORIA", "PREPA", "PREPA ABIERTA",
                     "1ER SEMESTRE DE PREPARATORIA", "2O. SEM PREPARATORIA",
                     "3ER SEM PREPARATORIA", "3° SEMESTRE PREPARATORIA",
                     "5TO SEM BACHILLERATO", "BARCHILLERATO",
                     "1 PREPARATORIA", "1 SEM BACHILLERATO", "2DO SEM BACHILLERATO",
                     "2° SEMESTRE DE PREPARATORIA", "3° PREPARATORIA",
                     "6° SEMESTRE PREPARATORIA", "BACHILLERES",
                     "INGENIERIA TRUNCA", "PREAPARTORIA", "REAPRATORIA",
                     "PREPARATORIA ABIERTA", "1 SEM PREPARATORIA", "1ER. SEM PREPARATORIA",
                     "1ER. SEM. PREPARATORIA", "1° BACHILLERATO",
                     "1° SEMESTRE DE PREPARATORIA", "2. BACHILLERATO",
                     "2DO BACHILLERATO", "2DO SEM DE PREPARATORIA",
                     "3ER. SEM. PREPARATORIA", "4O. SEM. PREPARATORIA",
                     "BACHUILLERATO", "CARRERA TECNICA TRUNCA",
                     "COBAEM", "LIC TRUNCA", "LICENCIATURA INCOMPLETA",
                     "PERPARATORIA", "PREPAPRATORIA", "PREPATORIA",
                     "PRERATORIA", "1 AÑO PREPARATORIA", "1 ER. SEM BACHILLERATO",
                     "1 SEMESTRE PREPARATORIA", "1ER SEM DE PREPARATORIA", "1ER SEM. PREPARATORIA",
                     "1O. DE PREPARATORIA", "1° BACHILLERES", "1° DE PREPARATORIA",
                     "2 PREPARATORIA", "2 SEM. BACHILLERATO", "2DO SEMESTRE PREPARATORIA", 
                     "2DO. SEMESTRE DE BACHILLERATO", "2O. SEM BACHILLERATO",
                     "2° BACHILLERATO", "3ER SEM. BACHILLERATO", "3ER. SEM BACHILLERATO",
                     "3ER. SEM. BACHILLERATO", "3° SEM PREPARATORIA", "3° SEMESTRE DE PREPARATORIA",
                     "4 SEM. BACHILLERATO", "4TO SEMESTRE BACHILLERATO", "6O. SEM PREPARATORIA",
                     "BACHILLERTO", "BACHLLERATO", "LIC INCOMPLETA", "LIC. TRUNCA", "PREPARARATORIA",
                     "PREPARARTORIA", "PREPARATIORIA", "PREPARATIRIA", "PREPARATORIA TERMINADA",
                     "PREPARATORIAS", "PREPARTATORIA", "PREPEARATORIA", "PREPRATORIA",
                     "PRIMER SEMESTRE DE PREPA", "PRIMERO DE PREPARATORIA", "PRPARATORIA",
                     "SPREPARATORIA", "SUPERIOR", "1 AÑO BACHILLERATO", "1 SEM DE BACHILLERATO (ENFERMERIA)",
                     "1 SEM. BACHILLERATO", "1. PREPARATORIA", "1. SEM. BACHILLERATO",
                     "1ER CUATRIMESTRE PREPARATORIA", "1ER SE. BACHILLERATO", "1ER SEM BACHILLERATO",
                     "1ER SEM PREPA", "1ER SEM PREPARATORIA", "1ER SEM. BACHILLERATO",
                     "1ER SEMESTRE BACHILLERATO", "1ER SEMESTRE PREPA", "1O. SEM DE BACHILLERATO",
                     "1PREPARATORIA", "1RO DE BACHILLERATO", "1RO DE PREPARATORIA",
                     "1RO PREPARATORIA", "1RO SEM. BACHILLERATO", "1RO. DE PREPARATORIA",
                     "1° AÑO DE BACHILLERATO", "1° AÑO PREPARATORIA", "1° SEM BACHILLERATO",
                     "1° SEMESTRE BACHILLERATO", "1° SEMESTRE BACHILLERES", "1° SEMESTRE DE BACHILLER",
                     "1° SEMESTRE DE BACHILLERATO", "2 AÑO PREPARATORIA", "2 SEM. DE PREPARATORIA",
                     "2 SEMESTRE DE POREPARTORIA", "2 SEMESTRE DE PREPARATORIA", "2 SEMESTRE PREPARATORIA",
                     "2 ° SEMESTRE PREPARATORIA", "2. SEM. BACHILLERATO", "2DO SEM. BACHILLERATO", 
                     "2DO SEM. DE BACHILLERATO", "2DO SEMESTRE DE BACHILLERATO", "2DO SEMESTRE DE PREPA",
                     "2DO. SEM BACHILLERATO", "2DO. SEM. BACHILLERATO", "2DO. SEMESTRE BACHILLERATO",
                     "2O. BACHILLERATO", "2O. PREPARATORIA", "2O. SEM. DE PREPARATORIA", "2O. SEM. PREPARATORIA",
                     "2SEM. PREPARATORIA", "2° AÑO BACHILLERATO", "2° SEM PREPARATORIA", "2° SEM. PREPARATORIA",
                     "2° SEMESTRE BACHILLERATO", "2° SEMESTRE DEW PREPARATORIA", "3. SEM PREPARATORIA",
                     "3. SEM. BACHILLERATO", "3ER SEM BACHILLERATO", "3ER SEMESTRE CCHVALLEJO",
                     "3ER SEMESTRE DE PREPA", "3ER SEMESTRE DE PREPARATORIA", "3ER SEMESTRE PREPA",
                     "3ER. SEM PREPA", "3ERO DE PREPARATORIA", "3R SEMESTRE PRORA", "3R SM BACHILLERATO",
                     "3R0 PREPARATORIA", "3RO BACHILLERATO", "3RO DE BACHILLERATO", 
                     "3° SEMESTRE BACHILLERATO", "4 SEM PREPARATORIA", "4. PREPARATORIA",
                     "4.SEM. BACHILLERATO", "4O. SEM PREPARATORIA", "4O. SEMESTRE BACHILLERATO",
                     "4TO CUATRIMESTRE BACHILLERATO", "4TO DE PREPARATORIA", "4TO SM BACHILLERATO",
                     "4° SEM. PREPARATORIA", "4° SEMESTRE BACHILLER", "4° SEMESTRE DE BACHILLERATO",
                     "4° SEMESTRE DE PREPARATORIA", "4°SEMESTRE PREPARATORIA", "5 SEM BACHILLERATO",
                     "5 SEM. PREPARATORIA", "5. BACHILLERATO", "5O. SEM PREPARATORIA", "5O. SEM. PREPARATORIA",
                     "5TO DE BACHILLERATO", "5TO SEM. BACHILLERATO", "5TO SEM. DE PREPARATORIA",
                     "5TO SEMESTRE BACHILLERATO", "5TO SEMESTRE PREPARATORIA", "5TO. SEM BACHILLERATO",
                     "5° SEM PREPARATORIA", "5° SEMESTRE BACHILLERATO",
                     "5° SEMESTRE DE BACHILLERATO", "5° SEMESTRE DE PREPARATORIA", "6 PREPARATORIA",
                     "6 SEM PREPA", "6TO SEM BACHILLERATO", "6TO SEM. BACHILLERATO", "6TO SEMESTRE PREPARATORIA",
                     "6° SEM BACHILLERATO", "6° SEMESTRE BACHILLERATO", "6° SEMESTRE CCH", "6° SEMESTRE DE PREPARATORIA",
                     "7. BACHILLERATO", "ARQUITECTURA TRUNCA", "BACHIILLERATO", "ACHILLER SISTEMA ABIERTO","BACHILLERAO",
                     "BACHILLERARO", "BACHILLERATO 1ER SEM", "BACHILLERATO COLEGIO MEXIQUENCE", "BACHILLERATO EN CURSO",
                     "BACHILLERATO EN LINEA", "BACHILLERATO PARA ADULTOS", "BACHILLERATO TERMINADO", "BACHILLERRES",
                     "BACHILLERTAO", "BACHILLERTATO", "BACHILLETARO", "BACSOL", "BAHILLERATO", "BAHILLERATO.",
                     "BAHILLERATO.", "BARCHILLERTO", "BCHILLERATO", "BECHILLERATO", "C.C.H. VALLEJO.",
                     "CARRERA TEC TRUNCA", "CARRERA TECNIA INCOMPLETA", "CARRERA TECNICA TRABAJO SOCIAL TRUNCA",
                     "CARRERA TRUNCA COMPU", "CARRERA TRUNCA CONTABILIDAD",
                     "CARRERA TRUNCA EN PUERICULTURA", "CARRERA TRUNCA VETERINARIA", "CARRERA TÈCNICA TRUNCA", "CARRET TRUNCA",
                     "CONTABILIDAD TRUNCA", "CONTADURIA TRUNCA", "CUARTO SEMESTRE DE PREPARATORIA",
                     "CURSANDO PREPARATORIA", "ER SEMESTRE BACHILLERATO", "GASTRONOMIA TRUNCA", "IER SEMESTRA PREPARATORIA",
                     "ING. QUIMICA TRUNCA", "LIC. ADMINISTRACIÓN TRUNCA", "LIC. DERECHO TRUNCA", "LIC. EN DERECHO TRUNCA",
                     "LIC. EN TURISMO TRUNCA", "LIC. ENFERMERIA TRUNCA", "LIC. MERCADOTECNIA TRUNCA", "LIC.TRUNCA",
                     "LICENCIATURA TRUCA", "LICENCIATURA TRUNCA ACTUARIA", "LICENCIATURA TRUNCA ADMON", "LICENCIATURA TRUNCA DER",
                     "LICENCIATURA TRUNCA EN DERECHO", "LICENCIATURA TRUNCA MATEMATICAS", "LICENCIATURA TRUNCANO",
                     "LICENCITURA TRUNCA", "LIENCIATURA TRUNCA", "LINCENCIATURA TRUNCA", "MEDIA SUPERIOR",
                     "MEDICINA TRUNCA", "PEPREPARATORIA", "PREPA CBT", "PREPA SEXTO", "PREPAPATORIA",
                     "PREPAPRATORI", "PREPARARORIA", "PREPARATORIA 1", "PREPARATORIA 1 UAEM",
                     "PREPARATORIA 2DO SEM", "PREPARATORIA CECITEM CANAELAS", "PREPARATORIA PRIMER SEMESTRE",
                     "PREPARATORIA UAEM", "PREPARATORIA.", "PREPARATOROA", "PREPARATOTIA", "PREPARATRIA",
                     "PREPARETORIA", "PREPARSOL", "PREPARTORIA EN LINEA", "PREPERATORIA EN LINEA",
                     "PRIMER SEMESTRE DE BACHILLERATO", "PRIMER SEMESTRE DE PREPARATORIA",
                     "PRIMER SEMESTRE DEL BACHILLERATO", "PRPEPARATORIA", "TELEBACHILLERATO",
                      "TERCER SEMESTRE BACHILLERATO", "TERCERO DE BACHILLERATO", "TERCERO DE PREPARATORIA",
                     "TERER SMENTRE DE CCH", "UNIVERSIDAD INCOMPLETA", "UNIVERSIDAS TRUNCA",
                     "VETERINARIA TRUNCA", "PAR 1RO DE BACHILLERATO", "|° PREPARATORIA", "2° SEMESTRE PREPARATORIA",
                     "LIC. TRUNCA PSICOLOGIA", "PREAPRATORIA", "3 ° PREPARATORIA",
                     "1° PREPAPARTORIA", "BACHILLER SISTEMA ABIERTO")


tecnica <- list("CARRERA TECNICA", "TECNICO", "TECNICA", "CONALEP",
                "BACHILLERATO TECNICO", "CARRERA TÉCNICA", "SECUNDARIA TECNICA",
                "PREPARATORIA TECNICA", "TECNICO INDUSTRIAL", "1° SEMESTRE CONALEP",
                "1° SEMESTRE DE CARRERA TECNICA", "1°MER SEMESTRE CETIS",
                "2DO SEMESTRE DE LA VOCACIONAL", "2O. SEM. CONALEP",
                "2° SEMESTRE CONALEP", "3ER SEM CONALEP", "3ER SEMESTRE BACHILLERATO CONALEP",
                "3ER, SEM. CONALEP", "5° SEMESTRE CARRERA TECNICA ENFERMERIA", "6TO SEM BACHILLERATO CON CARRERA TECNICA",
                "BACHILLERATO CONALEP", "BACHILLERATO CONTADURIA", "BACHILLERATO ENFERMERIA",
                "BACHILLERATO TECNOLOGICO", "BACHILLERATO TÉCNICO", "CARRERA COMERCIAL", "CARRERA COMERCIAL EN SECRETARIADO",
                "CARRERA EJECUTIVA", "CARRERA TECNICA CONTABILIDAD", "CARRERA TECNICA DE ENFERMERIA",
                "CARRERA TECNICA DE TORNOS", "CARRERA TECNICA EN ADMINISTRACION", "CARRERA TECNICA EN ARQUITECTURA",
                "CARRERA TECNICA EN CONSEJERIA DE ADICCIONES", "CARRERA TECNICA EN HOTELERIA Y RESTAURANTERIA",
                "CARRERA TECNICA EN INFORMATICA", "CARRERA TECNICA EN MECANICA ELECTRICA", "CARRERA TECNICA ENFERMERIA",
                "CARRERA TECNICA ESTILISTA", "CARRERA TECNICA MECANICA AUTOMOTRIZ", "CARRERA TECNICA QUIMICA INDUSTRIAL",
                "CARRERA TECNICA SECRETARIADO", "CARRERA TECNICA SECRETARIAL", "CARRERA TECNICA SECRETARIAL",
                "CARRERA TECNICA URGENCIAS MEDICAS Y RADIOLOGO", 
                "CARRERA TECNICO EN ENFERMERIA",  "CARRERA TÈCNICA", "CARRETA TECNICA", "CONALEP 081",
                "CONALEP 1ER SEM", "DERECHO EN UNITEC", "ESC. TECNICA N.24, SECUNDARIA", "LIC TECNICA",
                "NIVEL TECNICO", "PREPARA CONALEP", "SEGUNDO SEMESTRE DE PREPARATORIA", "TEC EN CONTABILIDAD",
                "TEC EN ENFERMERIA", "TEC. SECRETARIADO", "TECNCO MECANICO", "TECNICA DENTAL",
                "TECNICA EN MECANICA", "TECNICA ENFERMERIA", "TECNICA PROFECIONAL", "TECNICO AUTOMOTRIZ",
                "TECNICO DE ENFERMERIA", "TECNICO ELECTRICISTA", "TECNICO ELECTRÓNICO", "TECNICO EN COMPUTACION.",
                "TECNICO EN EMERGENCIAS MEDICAS", "TECNICO EN ENFERMERIA", "TECNICO EN INFORMATICA",
                "TECNICO EN LINEA BLANCA", "TECNICO EN MAQUINAS Y HERRAMIENTAS", "TECNICO EN MECANICA",
                "TECNICO EN MECÁNICA", "TECNICO EN PROCESOS DE PRODUCCCION IDUSTRIALES",
                "TECNICO EN SERIGRAFIA", "TECNICO ESTILISTA", "TECNICO MEDIO SUPERIOR TRABAJO SOCIAL",
                "TECNICO PROFESIONAL", "TECNICO PROFESIONAL PILOTO AVIADOR", "TECNOLOGICO DE TECAMAC",
                "TÉCNICO ELECTROMECÁNICO", "|° SEMESTRE DE CECYTEM",
                "CARRERA TECNICA EDUCADORA")


universidad <- list("LICENCIATURA", "UNIVERSIDAD", "LICENCIATURA TRUNCA",
                    "INGENIERIA", "INGENIERIA", "MAESTRIA", "LIC. EN DERECHO",
                    "DOCTORADO", "ESTUDIANTE DE LICENCIATURA",
                    "LICENCIATURA EN DERECHO", "LICENCIATURA EN PEDAGOGIA",
                    "CONTADURIA", "LIC EN DERECHO", "UNIVERSIDAD EN PROCESO",
                    "ARQUITECTO", "CONTADOR", "ING. CIVIL", "INGENIERO",
                    "INGENIERO INDUSTRIAL", "INGENIERO MECANICO", "LIC DERECHO",
                    "LIC. EN EDUCACION", "LICENCIATURA CRIMINOLOGIA", "LICENCITURA",
                    "UNIVERSITARIA", "1ER SEM LICENCIATURA", "7° SEMESTRE LIC. EN DERECHO",
                    "ARQUITECTURA", "CONTADOR PUBLICO", "DERECHO", "ING. EN SISTEMAS", "INGENERIA INDUSTRIAL",
                    "INGENIERA", "INGENIERIA INDUSTRIAL", "LIC EN ENFERMERIA",
                    "LIC. DERECHO", "LIC. EN COMERCIO INTERNACIONAL", "LIC. EN COMUNICACION",
                    "LIC. EN CRIMINOLOGIA", "LIC. EN INGENIERIA", "LIC. EN PEDAGOGIA",
                    "LIC. EN SEGURIDAD CIUDADANA", "LIC. EN TURISMO", "LIC. ENFERMERIA",
                    "LICENCIATURA ADMINISTRACION DE EMPRESAS", "LICENCIATURA DERECHO", "LICENCIATURA EN ADMINISTRACIÓN",
                    "LICENCIATURA EN CRIMINALISTICA", "LICENCIATURA MEDICINA", "LICENCIATURA PSICOLOGIA",
                    "LICENCIATURA TURISMO", "LICENTURA DERECHO", "LICIENCIATURA",
                    "LIECENCIATURA" , "MEDICO", "PASANTE EN ARQUITECTURA",
                    "PASANTE EN DERECHO", "PSICOLOGIA", "TERCER SEMESTRE DE PREPA",
                    "UNIVERSIDADA", "1 SEM LIC.", "1 SEM LICENCIATURA",
                    "1ER CUATRIMESTRE DERECHO", "1ER SEMESTRE DE LICENCIATURA",
                    "1° LIC. TRABAJO SOCIAL", "1° SEMESTRE DE INGENIERIA SISTEMAS COMPUTACIONALES",
                    "1° SEMESTRE DE UNIVERSIDAD", "1° SEMESTRE ING. QUIMICA", "1° SEMESTRE LIC. ENFERMERIA",
                    "1° SEMESTRE LIC. TURISMO", "2 CUATRI PEDAGOGIA", "2DO AÑO DE LICENCIATURA",
                    "2DO CUTRIMESTRE LICENCIATURA", "2° CUATRIMESTRE GASTRONOMÍA", 
                    "2° SEMESTRE DE LIC. EN DISEÑO", "2° SEMESTRE ING. EN SISTEMAS COMPUTACIONALES",
                    "2° SEMESTRE INGENIERIA INDUSTRIAL", "2° SEMESTRE LIC. PSICOLOGIA", 
                    "2° SEMESTRE LIC. PSICOLOGÍA", "2° SEMESTRE MEDICINA",
                    "3ER SEMESTRE DE ODONTOLOGÌA", "3ER SEMESTRE DOCENTE EDUCATIVO",
                    "3ER SEMESTRE TEC. CONTABILIDAD", "3ER. SEM LICENCIATURA",
                    "° CUATRIMESTRE LIC. DERECHO", "3° LIC. PSICOLOGÍA", "3° SEM. LIC. EN MECÁNICA",
                    "3° SEMESTRE UNIVERSIDAD", "4 CUARTRI LICENCIATURA", "4 SEM CONTABILIDAD",
                    "4TO CUATRIMESTRE CONTADURIA", "4TO SEMESTRE LICENCIATURA", "4° SEM. INFORMATICA",
                    "4° SEMESTRE DE LIC. EN DERECHO", "4° SEMESTRE LICENCIATURA", "5TO SEM LICENCIATURA",
                    "5TO SEM NUTRICION", "5TO. CUATRIMESTRE LIC. COMERCIO INTERNACIONAL ADUA", 
                    "5° CUATRIMESTRE LIC. PEDAGOGÍA", "5° SEMESTRE LIC.", "5° SMESTRE CONTABILIDAD",
                    "6TO SEM CONTADURIA", "6° SEM. LIC. PEDAGOGIA", "6° SEMESTRE SISTEMAS",
                    "7 LICENCIATURA", "7° CUATRIMESTRE DE DERECHO", "9NO CUATRIMESTRE LICENCIATURA", "9NO CUATRIMESTRE LICENCIATURA",
                    "9NO SEMESTRE LICENCIATURA", "9° LICENCIATURA", "9° SEM LICENCIATURA", "ABOGADO",
                    "ADMINISTRACION DE EMPRESAS", "ANTROPOLOGO", "ASTRONOMIA", "AURIGA INSTITUTO UNIVER", "CARRERA EN COMPUTACION",
                    "CONTADOR PUBLICO AUDITORv", "DERCHO", "DISEÑO GRAFICO", "DOCTORADO EN EDUCACION", "ESTUDIANT DE LICENCIATUA",
                    "ESTUDIANTE DE LA LICENCIATURA EN PSICOLOGIA", "FACULTAD", "FACULTAD DE ARTES PLASTICAS", "IN. INDUSTRIAL TRUNCA",
                    "INFORMATICA", "ING QUIMICO", "ING TRUNCA", "ING, SISTEMAS COMPUTACIONALES TRUNCA", "ING. COMUNICACION Y ELECTRONICA",
                    "ING. ELECTROMECANICO", "ING. EN AERONAUTICA", "ING. EN SISTEMAS COMPUTACIONALES",
                    "ING. EN SISTEMAS COMPUTACIONALES", "ING. INDUSTRIAL", "ING. INDUSTRIAL",
                    "ING. MECANICO", "ING. MECÁNICA", "ING. QUIMICO", "INGENIERA AMBIENTAL",
                    "INGENIERA INDUSTRIAL", "INGENIERA ROBOTICA", "INGENIERIA AUTOMOTRIZ",
                    "INGENIERIA CIVIL", "INGENIERIA EN SISTEMAS", "INGENIERIA QUIMICA",
                    "INGENIERO AGRONOMO", "INGENIERO AMBIENTAL", "INGENIERO CIVIL", "INGENIERO EN MECANICA",
                    "INGENIERO QUIMICO", "LCDA EN PEDAGOGIA", "LI. EN DOCENCIA", "LIC", "LIC ADMINISTRACION DE EMPRESAS TURISTICAS",
                    "LIC ARTES TEATRALES", "LIC CIENCIAS DE LA COMUNICACION", "LIC COMUNICACION", "LIC DISEÑO",
                    "LIC DISEÑO", "LIC EN COMERCIO", "LIC EN CONTADURIA", "LIC EN EDUCACION ESPECIAL",
                    "LIC EN LENGUA INGRESA", "LIC EN PSICOLOGIA", "LIC ING INDUSTRIAL", "LIC ODONTOLOGÍA",
                    "LIC PILOTO AVIADOR", "LIC PSICOLOGIA", "LIC REHABILITACION FISICA", "LIC. ADMINISTRACION DE EMPRESAS",
                    "LIC. ADMON INFORMATIVA", "LIC. ANESTECIOLOGO", "LIC. ANTROPOLOGIA", "LIC. ARQUITECTURA",
                    "LIC. ASISTENTE EDUCATIVO", "LIC. CIENCIAS DEL COMP HUMANO", "LIC. CONTADURIA TRUNCA", "LIC. EDUCACION",
                    "LIC. EDUCACIÓN", "LIC. EN ADMIN", "LIC. EN ADMINISTRACIÓN", "LIC. EN ADMINISTRACIÓN", "LIC. EN ADMON",
                    "LIC. EN ARQUITECTURA", "LIC. EN CIANCIAS DE LA EDUCACION", "LIC. EN CIENCIAS DE LA COMUNICACION",
                    "LIC. EN CIENCIAS DE LA EDUCACION", "LIC. EN COMUNICACION CUI", "LIC. EN CONTADURIA", "LIC. EN CONTADURÍA Y ADMON",
                    "LIC. EN DAMON", "LIC. EN DISEÑO E IMAGEN", "LIC. EN DISEÑO GRAFICO", "LIC. EN ENFERMMERIA", "LIC. EN GASTRONOMIA TRUNCA",
                    "LIC. EN INGENIERO EN PLASTICOS", "LIC. EN MERCADOCTENIA", "LIC. EN MERCADOTECNIA", "LIC. EN NEGOCIOS",
                    "LIC. EN ODONTOLOGIA", "LIC. EN PSICOLOGÍA", "LIC. EN PUBLICIDAD", "LIC. FISIOTERAPIA", "LIC. HISTORIA",
                    "LIC. ING. ELECTRONICA", "LIC. INGENIERIA BIOMEDICA IBERO SANTA FE", "LIC. MEDICINA", "LIC. MERCADOTECNIA",
                    "LIC. PEDAGOGIA", "LIC. PEDAGOGÍA", "LIC. PSICOPEDAGOGA", "LIC. QUIMICA", "LIC. RELACIONES INDUSTRIALES",
                    "LIC. RELACIONES INTERNACIONALES Y COMERCIO EXTERIO", "LICENCATURA", "LICENCIATRUA",
                    "LICENCIATRURA", "LICENCIATURA 2DO CUATRIMESTRE", "LICENCIATURA 2° SEMESTRE", "LICENCIATURA 8 SEM",
                    "LICENCIATURA 8° SEMESTRE", "LICENCIATURA ABOGADA", "LICENCIATURA ADMON", "LICENCIATURA ARQUITECTURA",
                    "LICENCIATURA COMUNICACION", "LICENCIATURA DE ECONOMIA", "LICENCIATURA DERECHO (PASANTE)",
                    "LICENCIATURA DISEÑO Y ARTE DIGITAL", "LICENCIATURA EDUCACION FISICA", "LICENCIATURA EN ADMINISTRACION",
                    "LICENCIATURA EN ADMON", "LICENCIATURA EN ADMON DE EMPRESAS", "LICENCIATURA EN CONTADURIA",
                    "LICENCIATURA EN DERECHO 8° SEMESTRE", "LICENCIATURA EN DISEÑO GRAFICO", "LICENCIATURA EN ECONOMIA",
                    "LICENCIATURA EN EDUCACION", "LICENCIATURA EN IGENIERIA AMBIENTAL", "LICENCIATURA EN LENGUAS LATINOAMERICANAS",
                    "LICENCIATURA EN LINEA", "LICENCIATURA EN MECATRONICA", "LICENCIATURA EN NUTRICION", "LICENCIATURA EN ODONTOLOGIA",
                    "LICENCIATURA EN PSICOLOGIA", "LICENCIATURA EN ROBOTICA INDUSTRIAL", "LICENCIATURA EN SECUNDARIA",
                    "LICENCIATURA EN TURISMO", "LICENCIATURA ENFERMERIA", "LICENCIATURA FINANZAS", "LICENCIATURA HOTELERIA",
                    "LICENCIATURA INFORMATICA", "LICENCIATURA ING INDUSTRIAL", "LICENCIATURA LENGUA ESPAÑOLA", "LICENCIATURA MECANICO AUTOMOTRIZ",
                    "LICENCIATURA MEDICO CIRUJANO", "LICENCIATURA MEDICO VETERINARIO", "LICENCIATURA NEGOCIOS INTERNACIONALES",
                    "LICENCIATURA NUTRICION", "LICENCIATURA PEDAGOGIA", "LICENCIATURA PRODUCCION MUSICAL", "LICENCIATURA PSICOLOGIA FACICO",
                    "LICENCIATURA UTEC TECAMAC", "LICENCIATURA, QF", "LICENCIATURA.", "LICENCITURA EN INGENIERIA",
                    "LICENCNIATURA", "LICENTURA", "LINCECIATURA", "MAESTRIA EN DERECHO", "MAESTRIA EN DOCENCIA",
                    "MTRO DISEÑO GRAFICO", "MTRO EN DERECHO", "MTRO EN TECNOLOGIA EDUCATIVA", "MÉDICO",
                    "NUTRICION 4 SEMESTRE", "PASANTE DE FILOSOFIA", "PASANTE DE INGENIERIA MECANICA",
                    "PASANTE DE LA LIC. EN QRQUITECTURA", "PASANTE DE LIC. EN DERECHO", "POSGRADO", "POST GRADO",
                    "PRIMER SMESTRE DE ODONTOLOGÍA", "QUIMICO", "RELACIONES INTERNACIONALES",
                    "SEGUNDO POLITECNICO", "SOCIOLOGIA", "TEOLOGIA", "UNIVERSDAD", "UNIVERSIATARIO",
                    "UNIVIERSIDAD", "ÑIC. EM DISEÑO INDUSTRIAL",
                    "LIC. ADMINISTRACION", "LICENCIATURA EN ENFERMERIA", "3° CUATRIMESTRE LIC. DERECHO",
                    "CONTADOR PUBLICO AUDITOR")


sin_escolaridad <- list("ANALFABETA", "SIN INSTRUCCION", "NINGUNA",
                        "SIN INICIAR", "NO INICIADA", "NO ESTUDIA",
                        "NINGUNO", "SIN ESOLARIDAD", "SIN ESTUDIOS",
                        "ANAFALBETA", "ANALAFABETA", "SIN INSTRUCCIÓN",
                        "NINGUAN", "NNGUNA", "NO REFIERE", "NO TIENE", "0",
                        "ANALFABETO", "ESCPECIAL", "ESTIMULACION TEMPRANA",
                        "SIN ISTRUCCION", "2DO. DE KINDER TRUMCO", "NIGNUNO", 
                        "NIGUNA", "NINGNA", "NO ESCOLARIZADO", "PRE ESCOLAR INCOMPLETO",
                        "SIN EDUCACION", "SIN ESCOLARIDAD AUN", "SIN ESTRUCION", "SIN INSTRUCCION ACADEMICA",
                        "SIN INSTRUCCION ESCOLAR", "SIN INSTRUCCIÓN ACADÉMICA", 
                        "SIN INTRUCCION", "SOLO LO ENSEÑARON A LEER", "SABE LEER Y ESCRIBIR",
                        "SABE ESCRIBIR Y LEER", "SABE LEER", "SIN ESCOLARIDAD",
                        "SIN ESTUDIO")


otra_escolaridad <- list("CULTURA DE BELLEZA",
                         "ENFERMERIA", "ESTILISMO", "ESTILISTA", "CENTRO DE ATENCION MULTIPLE",
                         "EDUCACION INICIAL", "PROFESIONISTA", "SEGUNDO", "1ER SEMESTRE CBT",
                         "4 CUARTRI LICENCIATURA", "4TO SEMESTRE DE CBT", "4TO SEMESTRE",
                         "5 SEMESTRE", "5TO DE CBT", "5TO SEMESTRE", "5° SEMESTRE", "6 AÑO",
                         "6TO", "6TO AÑO", "6° SEMESTRE DE ENFERMERIA", "9", "AMRIA", "ASISTENTE EDUCATIVO",
                         "ASISTENTE EJECUTIVO", "AUXICLIAR ENFERMERIA", "AUXILIAR CONTABLE", "AYUDANTE DE CARNICERO.",
                         "BENITO JUARES", "CAM MEDIO BASICO", "CAT LABORAL", "CEBETA", "CECYTEM",
                         "COMERCIAL", "COMERCIO", "COMPUTACION", "CUARTO SEMESTRE", "CULTORA DE BELLEZA",
                         "CURSO DE FISIOTERAPIA", "CURSOS PODOLOGIA", "DOCENTE", "EDAYO", "EDUACION ESPECIAL",
                         "EDUCACION", "ESCUELA ESPECIAL", "ESCUELA LABORAL", "ESPECIAL", "ESPECIALES",
                         "ESPECIALIDA EN GINECOLOGIA", "ESPECIALIDAD", "ESPECIALIDAD EN TRAUMALOGÍA Y ORTOPEDIA",
                         "ESTADO DE MEXICO", "ESTANCIA", "ESTUDINTE", "FEBREZ LINEA", "LAE. TRUNCA",
                         "MAESTRA DE INGLES", "MUSICA", "NORMAL SUPERIOR", "NORMALISTA",
                         "PILOTO", "PREPARACION", "PREPARATORIA EDUCACION ESPECIAL", "PRIMARIA ESPECIAL",
                         "PRIMER GRADO", "PRMA", "PROFESIONAL", "PROFESOR", "PROFESORA", "RADIOTECNICO",
                        "SACERDOTE", "SEGUNDO AÑO DE NORMAL",
                         "SEMINARISTA", "SERVICIO PUBLICO", "SEVETA NO. 35", "SEXTO", "SOL",
                        "SOLTER", "SOLTERA", "TERCER GRADO", "TERCERO", "VOCACIONAL",
                        "VOCACIONAL TRUNCA", "VOVACIONAL",
                        "EDUCACION ESPECIAL", "EDPECIAL", "EDUCACION ESPECIL", "4 ENFERMERIA")




