---
title: "shap-rf"
output: html_document
date: "2023-05-15"
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE,
                      warning = FALSE,
                      cache = FALSE,
                      fig.width = 8, 
                      fig.height = 6)
```


```{r}
if(!require('pacman')) {install.packages('pacman')}
pacman::p_load(here, tidyverse, tidymodels, vip, DALEX, DALEXtra, lime)


desp_data <- read_rds(here("import", "output", "baseline.rds")) %>% 
  filter(YEAR_EVENTO >= 2006 & YEAR_EVENTO <= 2022 &
           LOCALIZADO_VIVO_MUERTO != "SIGUE DESAPARECIDA" & DIFF_DIAS >= 0 &
           DIFF_DIAS < 32929) %>% 
  add_column(runif = runif(nrow(.))) %>% 
  rename(RANDOM = runif)
```


# 2. SPLIT DATA  


```{r}
## prepare data 
final_df <- desp_data %>% 
  arrange(YEAR_EVENTO) %>% 
  na.omit() %>% 
  mutate_if(is.character, as.factor) %>% 
  mutate(LOCALIZADO_VIVO_MUERTO = 
           case_when(LOCALIZADO_VIVO_MUERTO == "VIVO" ~ "1",
                     LOCALIZADO_VIVO_MUERTO == "MUERTO" ~ "0",),
         LOCALIZADO_VIVO_MUERTO = 
           factor(LOCALIZADO_VIVO_MUERTO, levels = c("1", "0"))
         )
```




```{r}
set.seed(123)
splits  <- initial_time_split(final_df, strata = LOCALIZADO_VIVO_MUERTO)

desp_train <- training(splits)
desp_test <- testing(splits)
```




```{r}
set.seed(234)
desp_validation <- validation_time_split(desp_train, strata = LOCALIZADO_VIVO_MUERTO)
desp_validation
```


# Prepare model 
```{r}
# set up recipe and transformation steps and roles
ranger_recipe <- 
  recipe(formula = LOCALIZADO_VIVO_MUERTO ~ ., 
         data = desp_train) 

#define model
ranger_spec <- 
  rand_forest() %>% 
  set_mode("classification") %>% 
  set_engine("ranger", importance = "permutation")

#create workflow
ranger_workflow <- 
  workflow() %>% 
  add_recipe(ranger_recipe) %>% 
  add_model(ranger_spec) 

#fit the model
set.seed(712) # for reproducibility - random sampling in random forest choosing number of variables
ranger_fit <- ranger_workflow %>% 
  fit(desp_train)
```




# Shap

```{r}
rf_explain <- 
  explain_tidymodels(
    model = ranger_fit,
    data = desp_train %>% select(-LOCALIZADO_VIVO_MUERTO), 
    y = as.integer(desp_train$LOCALIZADO_VIVO_MUERTO),
    label = "rf"
  )
```



```{r}
new_obs <- desp_test %>% slice(305) 
```

```{r}
new_obs_two <- desp_test %>% slice(100) 
```


```{r}
#Change order
pp_rf_ord1 <- predict_parts(explainer = rf_explain,
                            new_observation = new_obs,
                            type = "break_down") 
# Break-down plot
plot(pp_rf_ord1)
```

```{r}
#Change order
pp_rf_ord2 <- predict_parts(explainer = rf_explain,
                            new_observation = new_obs_two,
                            type = "break_down") 
# Break-down plot
plot(pp_rf_ord2)
```




```{r}
rf_shap <-predict_parts(explainer = rf_explain,
                        new_observation = new_obs,
                        type = "shap",
                        B = 10 #number of reorderings - start small
)

plot(rf_shap)
```

```{r}
rf_shap <-predict_parts(explainer = rf_explain,
                        new_observation = new_obs_two,
                        type = "shap",
                        B = 10 #number of reorderings - start small
)

plot(rf_shap)
```



# Dalex 
```{r}
model_type.dalex_explainer <- DALEXtra::model_type.dalex_explainer
predict_model.dalex_explainer <- DALEXtra::predict_model.dalex_explainer

lime_rf <- predict_surrogate(explainer = rf_explain,
                             new_observation = new_obs %>%
                               select(-LOCALIZADO_VIVO_MUERTO), 
                             n_features = 5,
                             n_permutations = 1000,
                             type = "lime")
```


```{r}
plot(lime_rf) +
  labs(x = "Variable")
```



```{r}
lime_rf_two <- predict_surrogate(explainer = rf_explain,
                             new_observation = new_obs_two %>%
                               select(-LOCALIZADO_VIVO_MUERTO), 
                             n_features = 5,
                             n_permutations = 1000,
                             type = "lime")
```




```{r}
plot(lime_rf_two) +
  labs(x = "Variable")
```





































































