---
title: "vivos-topic-dummys"
author: "Jorge Ruiz"
date: "2023-07-11"
output: html_document
---


```{r}
if(!require('pacman')) {install.packages('pacman')}
pacman::p_load(here, tidyverse, tidymodels, vip,
               naniar, rlang, stringi,svglite, probably)


# function clean 
clean_text <- function(s){
      str_squish(tolower(stri_trans_general(s, "latin-ascii")))
       }



cobupem_data <- read_rds(here("join", "output", "cobupem_clean_final.rds")) %>%
  filter(year_evento >= 2006 & year_evento <= 2022 &
          localizado_vivo_muerto != "SIGUE DESAPARECIDA" & diff_dias >= 0 &
           diff_dias < 32929) %>% 
  add_column(runif = runif(nrow(.))) %>% 
  rename(RANDOM = runif) %>% 
  select(-expediente, -status, -localizado_fecha,
         -year_localizado, -municipio_evento,
         -fecha_evento,  -women_exec_mun_mx, -idunico) %>% 
  mutate(categoria = replace_na(categoria, "UNKNOWN"),
         fiscalia = replace_na(fiscalia, "UNKNOWN"),
         escolaridad_d = replace_na(escolaridad_d, "UNKNOWN"),
         iba_solo = replace_na(iba_solo, "UNKNOWN"),
         estado_civil_d = replace_na(estado_civil_d, "UNKNOWN"),
        localizado_vivo_muerto = 
           factor(localizado_vivo_muerto, levels = c("VIVO", "MUERTO")
         ),
         text_cobupem = clean_text(text_cobupem),
         text_domicilio = ifelse(grepl("domicilio", text_cobupem), 1, 0),
         text_casa = ifelse(grepl("casa", text_cobupem), 1, 0),
         text_hija = ifelse(grepl("hija", text_cobupem), 1, 0),
         text_menor = ifelse(grepl("menor", text_cobupem), 1, 0),
         text_encuentra = ifelse(grepl("encuentra", text_cobupem), 1, 0),
         text_momento = ifelse(grepl("momento", text_cobupem), 1, 0),
         text_solo = ifelse(grepl("solo", text_cobupem), 1, 0),
         text_albergue = ifelse(grepl("albergue", text_cobupem), 1, 0),
         text_nucleo = ifelse(grepl("nucleo", text_cobupem), 1, 0),
         text_paradero = ifelse(grepl("paradero", text_cobupem), 1, 0),
         text_regreso = ifelse(grepl("regreso", text_cobupem), 1, 0),
         text_bueno = ifelse(grepl("bueno", text_cobupem), 1, 0),
         text_reintegra = ifelse(grepl("reintegra", text_cobupem), 1, 0),
         text_fisica = ifelse(grepl("fisica", text_cobupem), 1, 0),
         text_miedo = ifelse(grepl("miedo", text_cobupem), 1, 0),
         text_aborto = ifelse(grepl("aborto", text_cobupem), 1, 0),
         text_dia = ifelse(grepl("dia", text_cobupem), 1, 0),
         text_municipio = ifelse(grepl("municipio", text_cobupem), 1, 0),
         text_desconoce = ifelse(grepl("desconoce", text_cobupem), 1, 0),
         text_nombre = ifelse(grepl("nombre", text_cobupem), 1, 0),
         text_mexico = ifelse(grepl("mexico", text_cobupem), 1, 0),
         text_numero = ifelse(grepl("numero", text_cobupem), 1, 0),
         text_lugar = ifelse(grepl("lugar", text_cobupem), 1, 0),
         text_investigacion = ifelse(grepl("investigacion", text_cobupem), 1, 0),
         text_fecha = ifelse(grepl("fecha", text_cobupem), 1, 0),
         text_zumpango = ifelse(grepl("zumpango", text_cobupem), 1, 0),
         text_anita = ifelse(grepl("anita", text_cobupem), 1, 0),
         text_desconocidas = ifelse(grepl("desconocidas", text_cobupem), 1, 0),
         text_micaela = ifelse(grepl("micaela", text_cobupem), 1, 0),
         text_desaparicion = ifelse(grepl("desaparicion", text_cobupem), 1, 0),
         text_fho = ifelse(grepl("fho", text_cobupem), 1, 0),
         text_vida = ifelse(grepl("vida", text_cobupem), 1, 0),
         text_semefo = ifelse(grepl("semefo", text_cobupem), 1, 0),
         text_forense = ifelse(grepl("forense", text_cobupem), 1, 0),
         text_cuerpo = ifelse(grepl("cuerpo", text_cobupem), 1, 0),
         text_generalizada = ifelse(grepl("generalizada", text_cobupem), 1, 0),
         text_defuncion = ifelse(grepl("defuncion", text_cobupem), 1, 0),
         text_fhm = ifelse(grepl("fhm", text_cobupem), 1, 0),
         text_cadaver = ifelse(grepl("cadaver", text_cobupem), 1, 0),
         text_defunsion = ifelse(grepl("defunsion", text_cobupem), 1, 0),
         text_accidente = ifelse(grepl("accidente", text_cobupem), 1, 0)
           )  %>% 
  mutate_if(is.character, as.factor) %>% 
  mutate_if(is.numeric, funs(replace(., is.na(.), median(., na.rm = TRUE)))) %>% 
  drop_na(inegi)  %>% 
  arrange(year_evento)  %>% 
  select(-inegi, -text_cobupem)
```


```{r}
# Files -------------------------------------------------------------------
files <- list(roc_plot = here("output-models", "rocauc-plot."),
              vip_plot = here("output-models", "vip-plot."),
              cal_plot = here("output-models", "calibration-plot.")
              )




devices <- c("png", "svg")
```



# split data

```{r}
set.seed(123)
splits  <- initial_time_split(cobupem_data, strata = localizado_vivo_muerto)

cobupem_train <- training(splits)
cobupem_test <- testing(splits)
```



```{r}
cobupem_train %>% count(year_evento, sort = T)
```




```{r}
set.seed(234)
cobupem_validation <- validation_time_split(cobupem_train, strata = localizado_vivo_muerto)
cobupem_validation
```



# Prepare model

```{r}
## Random forest 
rf_spec <- rand_forest() %>%
  set_mode("classification") %>%
  set_engine("ranger", importance = "permutation")

rf_spec
```




```{r}
desp_wf <- workflow() %>%
  add_formula(localizado_vivo_muerto ~ .)

desp_wf
```

### Fit models on traint/validation

```{r}
doParallel::registerDoParallel()

rf_rs <- desp_wf %>%
  add_model(rf_spec) %>%
  fit_resamples(
    resamples = cobupem_validation,
    control = control_resamples(save_pred = TRUE),
    metrics = metric_set(roc_auc, accuracy, f_meas, bal_accuracy, sensitivity, specificity)
  )

rf_rs
```




# Evaluate 
```{r}
collect_metrics(rf_rs)
```





```{r}
collect_metrics(rf_rs) %>% 
  select(.metric, mean) %>% 
  filter(.metric == "sensitivity" | .metric == "specificity") %>% 
  pivot_wider(names_from = .metric,
              values_from = mean) %>% 
  mutate(gmean = sqrt(sensitivity*specificity))
```


```{r}
rf_rs %>%
  conf_mat_resampled()
```


```{r}
cal_plot_breaks(rf_rs) +
  labs(title = "Calibration plot on train set",
       subtitle = "Model 4 (topic modeling)")

```



```{r}
rf_rs %>%
  collect_predictions() %>%
  group_by(id) %>%
  roc_curve(localizado_vivo_muerto, .pred_VIVO) %>%
  mutate(model = "Random Forest")  %>%
  ggplot(aes(1 - specificity, sensitivity, color = id)) +
  geom_abline(lty = 2, color = "gray80", size = 1.5) +
  geom_path(show.legend = FALSE, alpha = 0.6, size = 1.2) +
  coord_equal() +
  theme_minimal(base_family = "Courier New") +
  theme(plot.title = element_text(face = "bold", hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        axis.text.x = element_text(face = "bold"),
        legend.position = "top") +
  labs(title = "ROC AUC best performing model",
       subtitle = "Model 4 (topic modeling)",
       y = NULL, x = NULL)

#walk(devices, ~ ggsave(filename = file.path(paste0(files$roc_plot, .x)),
 #                  device = .x, width = 10, height = 8))
```


# Test 
```{r}
### Test set 
desp_final <- desp_wf %>%
  add_model(rf_spec) %>%
  last_fit(splits,
           metrics = metric_set(roc_auc, accuracy, f_meas, bal_accuracy, sensitivity, specificity)
           )

desp_final
```



```{r}
collect_metrics(desp_final)
```




```{r}
collect_metrics(rf_rs) %>% 
  select(.metric, mean) %>% 
  filter(.metric == "sensitivity" | .metric == "specificity") %>% 
  pivot_wider(names_from = .metric,
              values_from = mean) %>% 
  mutate(gmean = sqrt(sensitivity*specificity))
```



```{r}
collect_predictions(desp_final) %>%
  conf_mat(localizado_vivo_muerto, .pred_class)
```

```{r}
cal_plot_breaks(desp_final) +
  labs(title = "Calibration plot on test set",
       subtitle = "Model 4 (topic modeling)")

walk(devices, ~ ggsave(filename = file.path(paste0(files$cal_plot, .x)),
                   device = .x, width = 10, height = 8))
```





```{r}
## OJO LO ESTO NO PASA CUANDO USO IMPURITY EN LUGAR DE PERMUTATION COMO MÉTODO PARA RF
## ¿QUÉ SE HACE?
## https://alexisperrier.com/datascience/2015/08/27/feature-importance-random-forests-gini-accuracy.html

desp_final %>%
 extract_fit_parsnip() %>% 
  vip() +
  theme_minimal() +
  labs(title = "Variable importance on test set",
      subtitle = "Model 4 (Topic modeling)")

#walk(devices, ~ ggsave(filename = file.path(paste0(files$vip_plot, .x)),
 #               device = .x, width = 10, height = 8))
```


