---
title: "vivos-missforest-munis"
author: "Jorge Ruiz"
date: "2023-06-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE,
                      warning = FALSE,
                      cache = FALSE,
                      fig.width = 8, 
                      fig.height = 6)
```




```{r}
if(!require('pacman')) {install.packages('pacman')}
pacman::p_load(here, tidyverse, tidymodels, vip,
               naniar, rlang, themis)


cobupem_data <- read_rds(here("impute", "output", "cobupem_imputed_forest.rds")) %>%
  filter(year_evento >= 2006 & year_evento <= 2022 &
          localizado_vivo_muerto != 2 & diff_dias >= 0 &
           diff_dias < 32929) %>% 
  add_column(runif = runif(nrow(.))) %>% 
  rename(RANDOM = runif) %>% 
  select(-expediente, -status, -localizado_fecha,
         -text_cobupem, -year_localizado, -municipio_evento,
         -fecha_evento,  -women_exec_mun_mx, -idunico, -inegi,
         -fiscalia, -categoria) %>% 
  arrange(year_evento)  %>% 
  mutate(localizado_vivo_muerto = as.factor(localizado_vivo_muerto),
    localizado_vivo_muerto = 
           factor(localizado_vivo_muerto, levels = c(3,1))
         ) 
```




# split data

```{r}
set.seed(123)
splits  <- initial_time_split(cobupem_data, strata = localizado_vivo_muerto)

cobupem_train <- training(splits)
cobupem_test <- testing(splits)
```



```{r}
cobupem_train %>% count(year_evento, sort = T)
```


```{r}
set.seed(234)
cobupem_validation <- validation_time_split(cobupem_train, strata = localizado_vivo_muerto)
cobupem_validation
```



# Prepare model

```{r}
## Random forest 
rf_spec <- rand_forest() %>%
  set_mode("classification") %>%
  set_engine("ranger", importance = "permutation")

rf_spec
```


```{r}
desp_wf <- workflow() %>%
  add_formula(localizado_vivo_muerto ~ .)

desp_wf
```


### Fit models on traint/validation

```{r}
rf_rs <- desp_wf %>%
  add_model(rf_spec) %>%
  fit_resamples(
    resamples = cobupem_validation,
    control = control_resamples(save_pred = TRUE),
    metrics = metric_set(roc_auc, accuracy, f_meas, bal_accuracy, sensitivity, specificity)
  )

rf_rs
```




# Evaluate 
```{r}
collect_metrics(rf_rs)
```



```{r}
collect_metrics(rf_rs) %>% 
  select(.metric, mean) %>% 
  filter(.metric == "sensitivity" | .metric == "specificity") %>% 
  pivot_wider(names_from = .metric,
              values_from = mean) %>% 
  mutate(gmean = sqrt(sensitivity*specificity))
```


```{r}
rf_rs %>%
  conf_mat_resampled()
```



```{r}
rf_rs %>%
  collect_predictions() %>%
  group_by(id) %>%
  roc_curve(localizado_vivo_muerto, .pred_3) %>%
  mutate(model = "Random Forest")  %>%
  ggplot(aes(1 - specificity, sensitivity, color = id)) +
  geom_abline(lty = 2, color = "gray80", size = 1.5) +
  geom_path(show.legend = FALSE, alpha = 0.6, size = 1.2) +
  coord_equal() 

#walk(devices, ~ ggsave(filename = file.path(paste0(files$roc_plot, .x)),
 #                  device = .x, width = 10, height = 8))
```



# Test 
```{r}
### Test set 
desp_final <- desp_wf %>%
  add_model(rf_spec) %>%
  last_fit(splits,
           metrics = metric_set(roc_auc, accuracy, f_meas, bal_accuracy, sensitivity, specificity)
           )

desp_final
```





```{r}
collect_metrics(desp_final)
```



```{r}
collect_metrics(rf_rs) %>% 
  select(.metric, mean) %>% 
  filter(.metric == "sensitivity" | .metric == "specificity") %>% 
  pivot_wider(names_from = .metric,
              values_from = mean) %>% 
  mutate(gmean = sqrt(sensitivity*specificity))
```


```{r}
collect_predictions(desp_final) %>%
  conf_mat(localizado_vivo_muerto, .pred_class)
```

```{r}
## OJO LO ESTO NO PASA CUANDO USO IMPURITY EN LUGAR DE PERMUTATION COMO MÉTODO PARA RF
## ¿QUÉ SE HACE?
## https://alexisperrier.com/datascience/2015/08/27/feature-importance-random-forests-gini-accuracy.html

desp_final %>%
 extract_fit_parsnip() %>% 
  vip() +
  theme_minimal() +
  labs(title = "Variable importance on test set")

#walk(devices, ~ ggsave(filename = file.path(paste0(files$vip_plot, .x)),
 #               device = .x, width = 10, height = 8))
```